services:
  - type: web
    name: moodle
    env: docker
    plan: free
    repo: https://github.com/AbdelazizEl7or/moodle
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
